spring:
  datasource:
    url: ${DATABASE_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}