spring:
  # Railway PostgreSql DB 연결 설정
  datasource:
    url: ${DATABASE_URL}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
